const productData = [
  {
    id: 1,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "판매",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 2,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 3,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 4,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "판매",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 5,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 6,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 7,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 8,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 9,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
  {
    id: 10,
    title: "웨스트우드",
    subtitle: "Viviene westwood",
    rental: "대여",
    price: "12000",
    view: 22,
    like: 1,
  },
];

export const tabData = {
  category: ["상의", "하의", "아우터", "가방", "기타"],
  style: [
    "뉴요커",
    "레트로",
    "캐주얼",
    "미니멀",
    "모던",
    "페미닌",
    "보헤미안",
    "비즈니스",
    "톰보이",
    "빈티지",
    "아메카지",
    "스트릿",
    "spa",
    "여성 국내 브랜드",
    "남성 국내 브랜드",
    "고프코어/y2k",
    "프레피룩",
    "페미닌",
    "고스패션",
    "펑크",
    "히피",
  ],
  brand: [
    "브랜드1",
    "브랜드2",
    "브랜드3",
    "브랜드4",
    "브랜드5",
    "브랜드6",
    "브랜드7",
    "브랜드8",
    "브랜드9",
    "브랜드10",
    "브랜드11",
    "브랜드12",
    "브랜드13",
    "브랜드14",
    "브랜드15",
    "브랜드16",
    "브랜드17",
    "브랜드18",
    "브랜드19",
    "브랜드20",
  ],
  rental: ["대여 가능", "대여 불가능"],
};

const LOW = "30,000 이하";
const MEDIUM = "30,000 ~ 100,000";
const HIGH = "100,000 이상";
export const priceList = [LOW, MEDIUM, HIGH];

export default productData;
