export const tabData = {
  category: ["상의", "하의", "아우터", "가방", "기타"],
  style: [
    "뉴요커",
    "미니멀",
    "보헤미안",
    "비즈니스",
    "톰보이",
    "빈티지",
    "아메카지",
    "스트릿",
    "SPA",
    "고프코어/y2k",
    "프레피룩",
    "페미닌",
    "펑크",
    "히피",
    "캐주얼",
    "귀여운",
    "몽환적인",
    "자유로운",
    "엘레강스",
    "섹시",
    "모노톤",
    "파스텔톤",
    "비비드톤",
    "딥톤",
    "팝칼라",
    "10대",
    "20대",
    "30대",
    "40대",
    "50대 이상",
  ],
  brand: [
    "Nike",
    "Stussy",
    "Chanel",
    "Japanese Vintage",
    "Gucci",
    "Balenciaga",
    "Supreme",
    "Vivinne Westwood",
    "Commee des Garcons",
    "Oakley",
    "MaisonMargiela",
    "Reebok",
    "Saint Laurent",
    "Louis Vuitton",
    "Givenchy",
    "Burberry",
    "Alexander McQueen",
    "Celine",
    "Kenzo",
    "Stella McCartney",
    "Marc Jacobs",
    "Michael Kors",
    "Tommy Hilfiger",
    "Coach",
    "Tory Burch",
  ],
  rental: ["대여 가능", "대여 불가능"],
};

const LOW = "30,000 이하";
const MEDIUM = "30,000 ~ 100,000";
const HIGH = "100,000 이상";
export const priceList = [LOW, MEDIUM, HIGH];
